name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: messages
        ports:
          - 5432:5432

      zookeeper:
        image: bitnami/zookeeper:latest
        env:
          ALLOW_ANONYMOUS_LOGIN: 'yes'
        ports:
          - 2181:2181

      kafka:
        image: bitnami/kafka:latest
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
        ports:
          - 9092:9092

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.2

    - name: Deploy app
      run: docker build -f Dockerfile.app -t app . && docker run -ePOSTGRES_USER:${{secrets.POSTGRES_USER}} -e POSTGRES_PASSWORD:${{secrets.POSTGRES_PASSWORD}} -e POSTGRES_HOST:postgres -e KAFKA_HOST:kafka -p 8090:8090 app
            
    - name: Deploy processor
      run: docker build -f Dockerfile.processor -t processor . && docker run -e POSTGRES_USER:${{secrets.POSTGRES_USER}} -e POSTGRES_PASSWORD:${{secrets.POSTGRES_PASSWORD}} -e POSTGRES_HOST:postgres -e KAFKA_HOST:kafka processor
        
    - name: Deploy migrator
      run: docker build -f Dockerfile.migrator -t migrator . && docker run -e POSTGRES_USER:${{secrets.POSTGRES_USER}} -e POSTGRES_PASSWORD:${{secrets.POSTGRES_PASSWORD}} -e POSTGRES_HOST:postgres migrator
        
        
